services:
  backend_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_1
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - MESSAGE=server-1

  backend_2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_2
    ports:
      - "3001:3000"
    networks:
      - app-network
    environment:
      - MESSAGE=server-2

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - backend_1
      - backend_2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
